---

apiVersion: v1

kind: Pod

metadata:

  name: rss-site

  labels:

    app: front-end

spec:

  containers:

    - name: front-end

      image: szupee.azurecr.io/webapp1

      ports:

        - containerPort: 80